[pytest]
testpaths = test_*.py
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Habilitar relatório detalhado
addopts = -v --cov=./ --cov-report=html:coverage_html --cov-report=term

# Ignorar arquivos específicos na cobertura
omit =
    */test_*.py
    */__pycache__/*